[[constraint]]
  version = "v1.0.3"
  #branch = "master"
  name = "go.mongodb.org/mongo-driver"

[[constraint]]
  branch = "master"
  name = "github.com/simagix/gox"

[[constraint]]
  version = "v0.1.0"
  name = "github.com/simagix/mongo-atlas"

[[constraint]]
  version = "v0.2.0"
  name = "github.com/simagix/mongo-ftdc"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
